trigger:
  branches:
    include:
      - "*"

stages:
  - stage: Build
    jobs:
      - job: Linux
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self
          - script: rustup update stable && rustup default stable
          - task: Cache@2
            inputs:
              key: 'linux-cargo-$(Build.SourcesDirectory)/Cargo.lock'
              path: |
                ~/.cargo/registry
                ~/.cargo/git
                target
          - script: cargo check --locked
          - script: cargo build --release --locked
          - publish: target/release
            artifact: forge-linux

      - job: macOS
        pool:
          vmImage: macos-latest
        steps:
          - checkout: self
          - script: rustup update stable && rustup default stable
          - task: Cache@2
            inputs:
              key: 'macos-cargo-$(Build.SourcesDirectory)/Cargo.lock'
              path: |
                ~/.cargo/registry
                ~/.cargo/git
                target
          - script: cargo check --locked
          - script: cargo build --release --locked
          - publish: target/release
            artifact: forge-macos

      - job: Windows
        pool:
          vmImage: windows-2022
        steps:
          - checkout: self
          - powershell: rustup update stable; rustup default stable
          - task: Cache@2
            inputs:
              key: 'windows-cargo-$(Build.SourcesDirectory)/Cargo.lock'
              path: |
                C:\Users\VssAdministrator\.cargo\registry
                C:\Users\VssAdministrator\.cargo\git
                target
          - powershell: cargo check --locked
          - powershell: cargo build --release --locked
          - publish: target/release
            artifact: forge-windows
