trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self

  - script: rustup update stable && rustup default stable

  - task: Cache@2
    inputs:
      key: 'linux-cargo-$(Build.SourcesDirectory)/Cargo.lock'
      path: |
        ~/.cargo/registry
        ~/.cargo/git
        target

  - script: cargo check --locked
  - script: cargo build --release --locked
  - publish: target/release
    artifact: forge-linux

  - script: sudo apt-get update && sudo apt-get install -y qemu qemu-user-static

  - script: rustup target add x86_64-apple-darwin
  - script: cargo build --release --locked --target x86_64-apple-darwin
  - publish: target/x86_64-apple-darwin/release
    artifact: forge-macos

  - script: rustup target add x86_64-pc-windows-gnu
  - script: cargo build --release --locked --target x86_64-pc-windows-gnu
  - publish: target/x86_64-pc-windows-gnu/release
    artifact: forge-windows
