version: 2.1

orbs:
  macos: circleci/macos@2.4.0

jobs:
  build-linux:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run:
          name: Install Rust Toolchain
          command: rustup target add x86_64-unknown-linux-gnu
      - run:
          name: Optimize Cargo
          command: |
            echo '[profile.release]' >> Cargo.toml
            echo 'opt-level = "z"' >> Cargo.toml
            echo 'strip = true' >> Cargo.toml
            echo 'lto = true' >> Cargo.toml
            echo 'codegen-units = 1' >> Cargo.toml
      - run:
          name: Build
          command: cargo build --release --target x86_64-unknown-linux-gnu
      - store_artifacts:
          path: target/x86_64-unknown-linux-gnu/release/rust
          destination: rust-x86_64-unknown-linux-gnu

  build-windows:
    machine:
      image: windows-server-2022-gui:current
    steps:
      - checkout
      - run:
          name: Install Rust
          command: choco install rust -y; refreshenv
      - run:
          name: Install Windows Toolchain
          command: rustup target add x86_64-pc-windows-gnu
      - run:
          name: Optimize Cargo
          command: |
            echo [profile.release] >> Cargo.toml
            echo opt-level = \"z\" >> Cargo.toml
            echo strip = true >> Cargo.toml
            echo lto = true >> Cargo.toml
            echo codegen-units = 1 >> Cargo.toml
      - run:
          name: Build
          command: cargo build --release --target x86_64-pc-windows-gnu
      - store_artifacts:
          path: target/x86_64-pc-windows-gnu/release/rust.exe
          destination: rust-x86_64-pc-windows-gnu

  build-macos:
    macos:
      xcode: "15.0.0"
    steps:
      - checkout
      - run:
          name: Install Rust
          command: |
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            source $HOME/.cargo/env
            rustup target add x86_64-apple-darwin aarch64-apple-darwin
      - run:
          name: Optimize Cargo
          command: |
            echo '[profile.release]' >> Cargo.toml
            echo 'opt-level = "z"' >> Cargo.toml
            echo 'strip = true' >> Cargo.toml
            echo 'lto = true' >> Cargo.toml
            echo 'codegen-units = 1' >> Cargo.toml
      - run:
          name: Build macOS x86_64
          command: cargo build --release --target x86_64-apple-darwin
      - run:
          name: Build macOS aarch64
          command: cargo build --release --target aarch64-apple-darwin
      - store_artifacts:
          path: target/x86_64-apple-darwin/release/rust
          destination: rust-x86_64-apple-darwin
      - store_artifacts:
          path: target/aarch64-apple-darwin/release/rust
          destination: rust-aarch64-apple-darwin

workflows:
  build-all:
    jobs:
      - build-linux
      - build-windows
      - build-macos
