name: Alter

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }} for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: ubuntu-latest
            target: wasm32-unknown-unknown
          - os: ubuntu-latest
            target: aarch64-linux-android
          - os: macos-latest
            target: aarch64-apple-ios

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install Android NDK
        if: contains(matrix.target, 'android')
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26b
          add-to-path: true

      - name: Cache Cargo registry + build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.target }}-cargo-

      - name: Verify lockfile is up to date
        run: cargo check --locked --target ${{ matrix.target }}

      - name: Build release
        run: cargo build --release --locked --target ${{ matrix.target }}

      - name: Zip Windows binary
        if: startsWith(matrix.os, 'windows')
        run: |
          mkdir artifact
          copy target\${{ matrix.target }}\release\alter.exe artifact\
          powershell Compress-Archive -Path artifact\* -DestinationPath alter-${{ matrix.os }}-${{ matrix.target }}.zip

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: alter-${{ matrix.os }}-${{ matrix.target }}
          path: |
            ${{ startsWith(matrix.os, 'windows') && format('alter-{0}-{1}.zip', matrix.os, matrix.target) || format('target/{0}/release/alter', matrix.target) }}
